<a href="https://colab.research.google.com/github/wonsik99/CNN-MSAIL/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)

PyTorch version: 2.9.0+cu126


# Creating and Initializing Tensors

### Basic Creation

In [ ]:
# From Python lists
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("From list:", tensor_from_list)

# From NumPy arrays
numpy_array = np.array([1, 2, 3, 4])
tensor_from_numpy = torch.from_numpy(numpy_array)
print("From NumPy:", tensor_from_numpy)

# 2D tensor (matrix)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("2D tensor:\n", matrix)

From list: tensor([1, 2, 3, 4])
From NumPy: tensor([1, 2, 3, 4])
2D tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


### Initialization Functions

In [ ]:
# Zeros tensor
zeros = torch.zeros(3, 4) # 3x4 matrix of zeros
print("Zeros tensor:\n", zeros)

# Ones tensor
ones = torch.ones(2, 3) # 2x3 matrix of ones
print("Ones tensor:\n", ones)

# Identity matrix
identity = torch.eye(3) # 3x3 identity matrix
print("Identity matrix:\n", identity)

# Random tensors
random_uniform = torch.rand(2, 3) # Uniform distribution [0, 1)
random_normal = torch.randn(2, 3) # Standard normal distribution
print("Random uniform:\n", random_uniform)
print("Random normal:\n", random_normal)

# Filled with a specific value
filled = torch.full((2, 3), 7.5) # 2x3 tensor filled with 7.5
print("Filled tensor:\n", filled)

# Range of values
range_tensor = torch.arange(0, 10, 2) # [0, 2, 4, 6, 8]
linspace_tensor = torch.linspace(0, 1, 5) # 5 evenly spaced values from 0 to 1
print("Range tensor:", range_tensor)
print("Linspace tensor:", linspace_tensor)

Zeros tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Random uniform:
 tensor([[0.1474, 0.1225, 0.1134],
        [0.6199, 0.9810, 0.8607]])
Random normal:
 tensor([[-1.0934,  0.1430, -1.9077],
        [ 1.1662, -1.6935, -1.0594]])
Filled tensor:
 tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])
Range tensor: tensor([0, 2, 4, 6, 8])
Linspace tensor: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


### Creating Tensors with Specific Properties

In [ ]:
# Create tensor with same shape as another
x = torch.randn(2, 3)
zeros_like_x = torch.zeros_like(x)
ones_like_x = torch.ones_like(x)
print("Original tensor:\n", x)
print("Zeros like x:\n", zeros_like_x)


x + ones_like_x

Original tensor:
 tensor([[ 2.0375, -0.2239,  0.5120],
        [-0.6859,  0.3379, -2.6207]])
Zeros like x:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[ 3.0375,  0.7761,  1.5120],
        [ 0.3141,  1.3379, -1.6207]])

# Properties

In [8]:
# Create a sample tensor
sample_tensor = torch.randn(3, 4, 5, device="cuda")

print("Shape:", sample_tensor.shape) # or sample_tensor.size()
print("Number of dimensions:", sample_tensor.dim())
print("Total number of elements:", sample_tensor.numel())
print("Data type:", sample_tensor.dtype)
print("Device:", sample_tensor.device)

# Change data type
float_tensor = sample_tensor.float()
int_tensor = sample_tensor.int()
print("Float tensor dtype:", float_tensor.dtype)
print("Int tensor dtype:", int_tensor.dtype)


Shape: torch.Size([3, 4, 5])
Number of dimensions: 3
Total number of elements: 60
Data type: torch.float32
Device: cuda:0
Float tensor dtype: torch.float32
Int tensor dtype: torch.int32


# Indexing and Slicing

### Basics

In [ ]:
# Create a 2D tensor for demonstration
matrix = torch.tensor([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])

print("Original matrix:\n", matrix)

# Access single elements
print("Element at [0, 1]:", matrix[0, 1]) # First row, second column
print("Element at [2, 3]:", matrix[2, 3]) # Third row, fourth column

# Access entire rows and columns
print("First row:", matrix[0, :]) # All columns of first row
print("Last column:", matrix[:, -1]) # All rows of last column
print("Second row:", matrix[1]) # Shorthand for matrix[1, :]

### More Advanced Stuff

In [ ]:
# Slice ranges
print("First two rows:\n", matrix[:2, :])
print("Last two columns:\n", matrix[:, -2:])
print("Middle elements:\n", matrix[1:3, 1:3])

# Step slicing
print("Every other column:\n", matrix[:, ::2])
print("Reverse order:\n", matrix[:-1:, :])

# Boolean indexing
mask = matrix > 6
print("Boolean mask:\n", mask)
print("Elements > 6:", matrix[mask])

# Fancy indexing
rows = torch.tensor([0, 2])
cols = torch.tensor([1, 3])
print("Elements at (0,1) and (2,3):", matrix[rows, cols])

### 3D Slicing

In [ ]:
# Create a 3D tensor
tensor_3d = torch.randn(2, 3, 4)
print("3D tensor shape:", tensor_3d.shape)

# Access different dimensions
print("First 'slice' along dim 0:\n", tensor_3d[0, :, :])
print("First column of each 2D slice:\n", tensor_3d[:, :, 0])
print("Center element of each slice:", tensor_3d[:, 1, 1])

# Reshaping and Permutations

### Reshaping Tensors

In [ ]:
# Create a sample tensor
original = torch.arange(12)
print("Original tensor:", original)
print("Original shape:", original.shape)

# Reshape to 2D
reshaped_2d = original.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape to 3D
reshaped_3d = original.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 for automatic dimension calculation
auto_reshape = original.reshape(4, -1) # 4 rows, automatically calculate columns
print("Auto-reshaped to 4x?:\n", auto_reshape)

# View vs Reshape
# view() requires contiguous memory, reshape() is more flexible
viewed = original.view(3, 4) # Same as reshape for contiguous tensors
print("Viewed as 3x4:\n", viewed)

### Squeezing and Unsqueezing

In [ ]:
# Create tensor with singleton dimensions
tensor_with_singleton = torch.randn(1, 3, 1, 4)
print("Original shape:", tensor_with_singleton.shape)

# Remove singleton dimensions
squeezed = tensor_with_singleton.squeeze()
print("After squeeze:", squeezed.shape)

# Remove specific dimension
squeezed_dim0 = tensor_with_singleton.squeeze(0)
print("Squeeze dim 0:", squeezed_dim0.shape)

# Add dimensions
unsqueezed = squeezed.unsqueeze(1)  # Add dimension at position 1
print("After unsqueeze at dim 1:", unsqueezed.shape)

# Alternative: use indexing with None
expanded = squeezed[:, None, :]  # Same as unsqueeze(1)
print("Using None indexing:", expanded.shape)

### Permutations and Transposing

In [ ]:
# Create a 3D tensor
tensor = torch.randn(2, 3, 4)
print("Original shape:", tensor.shape)

# Transpose (swap two dimensions)
transposed = tensor.transpose(0, 1)  # Swap dimensions 0 and 1
print("After transpose(0,1):", transposed.shape)

# For 2D tensors, you can use .T
matrix_2d = torch.randn(3, 4)
print("2D matrix shape:", matrix_2d.shape)
print("Transposed with .T:", matrix_2d.T.shape)

# Permute dimensions (rearrange all dimensions)
permuted = tensor.permute(2, 0, 1)  # New order: (4, 2, 3)
print("After permute(2,0,1):", permuted.shape)

# Multiple ways to achieve the same result
print("Original tensor shape:", tensor.shape)
print("transpose(0,2).transpose(0,1):", tensor.transpose(0, 2).transpose(0, 1).shape)
print("permute(1, 2, 0):", tensor.permute(1, 2, 0).shape)

# Tensor Operations

### Element-wise Operations

In [ ]:
# Create sample tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([2, 3, 4, 5])

print("a:", a)
print("b:", b)

# Basic arithmetic
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

# In-place operations (modify original tensor)
c = a.clone()  # Make a copy
c += 10  # In-place addition
print("After in-place addition:", c)

### Broadcasting

In [ ]:
# Broadcasting allows operations between tensors of different shapes
matrix = torch.ones(3, 4)
vector = torch.tensor([1, 2, 3, 4])
scalar = 5

print("Matrix shape:", matrix.shape)
print("Vector shape:", vector.shape)

# These operations broadcast automatically
result1 = matrix + vector  # Vector broadcasts to match matrix
result2 = matrix * scalar  # Scalar broadcasts to match matrix

print("Matrix + vector result shape:", result1.shape)
print("Matrix * scalar result shape:", result2.shape)

# Try it yourself!

### 1.

In [ ]:
# TODO: Create a 3x4 tensor filled with random numbers from a normal distribution
# Your code here:

# TODO: Create a 3x4 tensor filled with the value 2.5
# Your code here:

# TODO: Create a 1D tensor with values from 0 to 20 with step size 2
# Your code here:

# TODO: Add the first two tensors element-wise and print the result
# Your code here:'


### 2.

In [ ]:
# Given tensor
data = torch.tensor([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]])

print("Original data:\n", data)

# TODO: Extract the center 2x2 submatrix (should be [[7, 8], [12, 13]])
# Your code here:

# TODO: Get all elements in the last row except the first and last columns
# Your code here:

# TODO: Extract all even numbers using boolean indexing
# Your code here:

# TODO: Get elements at positions (0,1), (2,3), and (1,4)
# Your code here:


### 3.

In [ ]:
# Create a tensor representing a small "image" batch
batch_size, channels, height, width = 2, 3, 4, 4
images = torch.randn(batch_size, channels, height, width)
print("Images shape:", images.shape)

# TODO: Flatten each image while keeping the batch dimension
# Result should be shape (2, 48) - each image becomes a 48-element vector
# Your code here:

# TODO: Rearrange to put channels last (common for some frameworks)
# Change from (N, C, H, W) to (N, H, W, C)
# Your code here:

# TODO: Extract the first image and transpose its height and width
# Start with shape (3, 4, 4), end with shape (3, 4, 4) but H and W swapped
# Your code here:

# TODO: Reshape the entire batch into a single 2D tensor where each row is a pixel
# Final shape should be (32, 3) - 32 pixels total, 3 channels each
# Your code here:
