<a href="https://colab.research.google.com/github/wonsik99/cnn-msail/blob/main/pytorch_intro2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

# 1. Matrix Operations and Broadcasting

In [ ]:
# Create two random matrices
matrix_a = torch.randn(4, 3)
matrix_b = torch.randn(3, 4)
vector_c = torch.tensor([1.0, 2.0, 3.0])

print("Matrix A shape:", matrix_a.shape)
print("Matrix B shape:", matrix_b.shape)
print("Vector C shape:", vector_c.shape)

# TODO: Perform matrix multiplication between matrix_a and matrix_b
# Hint: Use torch.mm()
# Your code here:
matmul_result = torch.mm(matrix_a, matrix_b)
print(matmul_result)

# TODO: Add vector_c to each row of matrix_a using broadcasting
# Your code here:
add_vec = matrix_a + vector_c
print(add_vec)

# TODO: Calculate the element-wise square root of the absolute values of matrix_a
# Your code here:
sqrt_result = torch.sqrt(torch.abs(matrix_a))
print(sqrt_result)

Matrix A shape: torch.Size([4, 3])
Matrix B shape: torch.Size([3, 4])
Vector C shape: torch.Size([3])
tensor([[-0.7670,  0.8086,  1.5340, -3.3318],
        [ 3.1095, -1.8755, -1.1064,  0.8478],
        [ 1.5582,  0.9036, -0.0285, -0.2326],
        [-2.4599,  2.0901,  1.2450, -1.3944]])
tensor([[ 0.1568,  2.7176,  4.6372],
        [-1.0263,  1.4558,  3.3921],
        [ 1.1533,  2.9182,  1.6752],
        [ 2.7231,  2.8832,  2.5311]])
tensor([[0.9183, 0.8471, 1.2795],
        [1.4235, 0.7377, 0.6262],
        [0.3916, 0.9582, 1.1510],
        [1.3127, 0.9398, 0.6848]])


### Solutions for Exercise 1 (attempt it on your own first)

In [ ]:
# Solutions for Exercise 1:
# Matrix multiplication
matmul_result = torch.mm(matrix_a, matrix_b)  # or matrix_a @ matrix_b
print("Matrix multiplication result shape:", matmul_result.shape)

# Broadcasting addition
broadcast_result = matrix_a + vector_c
print("Broadcasted addition result:\n", broadcast_result)

# Element-wise square root of absolute values
sqrt_result = torch.sqrt(torch.abs(matrix_a))
print("Square root of absolute values:\n", sqrt_result)

# 2. More Indexing and Masking

In [19]:
# Create a sample dataset of exam scores. Each row represents a "student"
scores = torch.tensor([[85, 92, 78, 96, 88],
                      [76, 89, 94, 82, 91],
                      [90, 87, 85, 93, 89],
                      [82, 78, 91, 86, 94]])

print("Scores shape:", scores.shape)
print("Scores:\n", scores)

# TODO: Find all scores above 90 and replace them with 90
# Your code here:
# capped_scores = scores.clone()
# capped_scores[capped_scores > 90] = 90
# print("Capped scores:\n", capped_scores)
new_scores = scores.clone()
new_scores[new_scores > 90] = 90
print(new_scores)

# TODO: Get the index of the maximum score in each row
# Your code here:
max_indices = torch.argmax(scores, dim=1)
print(max_indices)

# TODO: Create a boolean mask for students (rows) who have at least 3 scores above 85
# Your code here:
mask = (scores > 85).sum(dim=1) >= 3
print(mask)

# TODO: Calculate the average score for each student, but only for scores <= 90
# Hint: Use masking to exclude high scores -- use float('nan') to set values to nan -- then calculate mean
# Your code here:
new_scores = scores.clone().float()
new_scores[new_scores > 90] = float('nan')
avg_scores = torch.nanmean(new_scores, dim=1)
print(avg_scores)

# TODO: Get the scores of the top 2 performing students (based on sum of all scores)
# Hint: Check out the pytorch documentation for torch.topk()
# Your code here:
total_scores = scores.sum(dim=1)
top_values, top_indices = torch.topk(total_scores, k=2)
top_2 = scores[top_indices]
print(top_2)

Scores shape: torch.Size([4, 5])
Scores:
 tensor([[85, 92, 78, 96, 88],
        [76, 89, 94, 82, 91],
        [90, 87, 85, 93, 89],
        [82, 78, 91, 86, 94]])
tensor([[85, 90, 78, 90, 88],
        [76, 89, 90, 82, 90],
        [90, 87, 85, 90, 89],
        [82, 78, 90, 86, 90]])
tensor([3, 2, 3, 4])
tensor([True, True, True, True])
tensor([83.6667, 82.3333, 87.7500, 82.0000])
Top 2 students' scores:
 tensor([[90, 87, 85, 93, 89],
        [85, 92, 78, 96, 88]])


### Solutions for Exercise 2 (attempt it on your own first)

In [18]:
# Solutions for Exercise 2:
# Grade capping
capped_scores = scores.clone()
capped_scores[capped_scores > 90] = 90
print("Capped scores:\n", capped_scores)

# Index of maximum score in each row
max_indices = torch.argmax(scores, dim=1)
print("Max score indices per student:", max_indices)

# Boolean mask for students with at least 3 scores above 85
above_85 = scores > 85
students_with_3_above_85 = torch.sum(above_85, dim=1) >= 3
print("Students with 3+ scores above 85:", students_with_3_above_85)

# Average score excluding scores above 90
masked_scores = scores.clone().float()
masked_scores[scores > 90] = float('nan')
averages = torch.nanmean(masked_scores, dim=1)
print("Averages excluding >90:", averages)

# Top 2 performing students
total_scores = torch.sum(scores, dim=1)
top_2_indices = torch.topk(total_scores, 2).indices
top_2_scores = scores[top_2_indices]
print("Top 2 students' scores:\n", top_2_scores)

Capped scores:
 tensor([[85, 90, 78, 90, 88],
        [76, 89, 90, 82, 90],
        [90, 87, 85, 90, 89],
        [82, 78, 90, 86, 90]])
Max score indices per student: tensor([3, 2, 3, 4])
Students with 3+ scores above 85: tensor([True, True, True, True])
Averages excluding >90: tensor([83.6667, 82.3333, 87.7500, 82.0000])
Top 2 students' scores:
 tensor([[90, 87, 85, 93, 89],
        [85, 92, 78, 96, 88]])


# 3. Concatenation and Stacking

In [ ]:
## Exercise 6: Tensor Concatenation and Stacking
# Create sample tensors
tensor1 = torch.randn(2, 3)
tensor2 = torch.randn(2, 3)
tensor3 = torch.randn(3, 3)

print("Tensor1:\n", tensor1)
print("Tensor2:\n", tensor2)
print("Tensor3:\n", tensor3)

# Hint: Check out the pytorch documentation for torch.cat() and torch.stack()

# TODO: Concatenate tensor1 and tensor2 along dimension 0 (rows)
# Your code here:

# TODO: Concatenate tensor1 and tensor3 along dimension 1 (columns)
# Your code here:

# TODO: Stack tensor1 and tensor2 to create a 3D tensor
# Try both dim=0 and dim=1 to see the difference
# Your code here:

# TODO: Create a list of 5 random tensors of shape (2, 4) and stack them
# to create a tensor of shape (5, 2, 4)
# Hint: Remember torch.randn() exists
# Your code here:


### Solutions for Exercise 3 (attempt it on your own first)

In [ ]:
# Solutions for Exercise 3:
# Concatenate along rows
concat_rows = torch.cat([tensor1, tensor2], dim=0)
print("Concatenated along rows shape:", concat_rows.shape)

# Concatenate along columns
concat_cols = torch.cat([tensor1, tensor3], dim=1)
print("Concatenated along columns shape:", concat_cols.shape)

# Stack tensors
stack_dim0 = torch.stack([tensor1, tensor2], dim=0)
stack_dim1 = torch.stack([tensor1, tensor2], dim=1)
print("Stacked dim=0 shape:", stack_dim0.shape) # shape (2, 2, 3)
print("Stacked dim=1 shape:", stack_dim1.shape) # shape (2, 2, 3)

# Create and stack multiple tensors
tensor_list = [torch.randn(2, 4) for _ in range(5)]
stacked_list = torch.stack(tensor_list, dim=0)
print("Stacked list shape:", stacked_list.shape) # shape (5, 2, 4)

# 4. Statistics in PyTorch

In [ ]:
### Exercise 7: Reduction Operations and
# Create a 3D tensor representing temperature data
# Shape: (days, locations, hours) = (7, 4, 24)
temperatures = torch.randn(7, 4, 24) * 10 + 20  # Mean ~20°C, std ~10°C

print("Temperature data shape:", temperatures.shape)
print("Sample temperatures for day 0, location 0:", temperatures[0, 0, :5])

# Hint: Check out pytorch documentation for torch.max(), torch.min(), torch.mean(), torch.std()
# Pay attention to the number of return values for torch.max() and torch.min()

# TODO: Calculate the average temperature for each day (across all locations and hours)
# Your code here:

# TODO: Find the maximum temperature recorded at each location across all days and hours
# Your code here:

# TODO: Calculate the standard deviation of temperatures for each location across all days/hours
# Your code here:

# TODO: Calculate the temperature range (max - min) for each day at each location
# Your code here:



### Solutions for Exercise 4 (attempt it on your own first)

In [ ]:
# Solutions for Exercise 4:
# Average temperature per day
daily_avg = torch.mean(temperatures, dim=(1, 2)) # Average over locations and hours
print("Daily average temperatures:", daily_avg)

# Maximum temperature per location
location_max, _ = torch.max(temperatures.view(7*24, 4), dim=0) # Reshape and find max
print("Maximum temperature per location:", location_max)

# Standard deviation per location
location_std = torch.std(temperatures.view(7*24, 4), dim=0)
print("Temperature std per location:", location_std)

# Temperature range per day per location
daily_max, _ = torch.max(temperatures, dim=2) # Max per day per location
daily_min, _ = torch.min(temperatures, dim=2) # Min per day per location
daily_range = daily_max - daily_min
print("Daily temperature range shape:", daily_range.shape)

# 5. Data Types and Weird PyTorch Memory Things

In [ ]:
### Exercise 8: Working with Different Data Types and Memory
# Create tensors with different data types
int_tensor = torch.randint(0, 100, (3, 4), dtype=torch.int32)
float_tensor = torch.randn(3, 4, dtype=torch.float64)
bool_tensor = torch.rand(3, 4) > 0.5

print("Int tensor:\n", int_tensor)
print("Float tensor:\n", float_tensor)
print("Bool tensor:\n", bool_tensor)

# Hint: Remember torch.clone() exists. What does it do?

# TODO: Convert the int_tensor to float and add 0.5 to all elements
# Your code here:

# TODO: Use the bool_tensor as a mask to set corresponding elements in float_tensor to 0
# Your code here:

# TODO: Create a tensor that shares memory with int_tensor and modify it
# Verify that changes affect the original tensor
# Your code here:

# TODO: Create an independent copy of float_tensor and verify changes don't affect original
# Your code here:


### Solutions for Exercise 5 (attempt it on your own first)

In [ ]:
# Solutions for Exercise 5:
# Convert to float and add 0.5
float_from_int = int_tensor.float() + 0.5
print("Int converted to float + 0.5:\n", float_from_int)

# Use boolean mask
masked_float = float_tensor.clone()
masked_float[bool_tensor] = 0
print("Masked float tensor:\n", masked_float)

# Shared memory view
shared_view = int_tensor.view(-1) # Flatten to 1D for simplicity (not needed)
shared_view[0] = 999
print("Original tensor after modifying view:\n", int_tensor)

# Independent copy
independent_copy = float_tensor.clone()
independent_copy[0, 0] = 999
print("Original float tensor unchanged:\n", float_tensor[0, 0])
print("Copy was modified:", independent_copy[0, 0])